name: Deploy to VPS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install frontend dependencies
      run: npm install
      
    - name: Build frontend
      run: npm run build
      
    - name: Install backend dependencies
      run: |
        cd backend
        npm install
        
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /var/www/jas-technologies
          
          # Handle git conflicts by resetting to remote
          sudo -u deploy git fetch origin
          sudo -u deploy git reset --hard origin/main
          
          # Install frontend dependencies and build
          sudo -u deploy npm install
          sudo -u deploy npm run build
          
          # Install backend dependencies
          cd backend
          sudo -u deploy npm install
          cd ..
          
          # Restart PM2 services
          sudo -u deploy pm2 restart all
          sudo systemctl reload nginx